# Mandatory settings

name: "Amir Sharif"
paginate: 25
paginate_path: "/posts/page/:num/"
url: "http://www.amirsharif.com"
blog_theme: light # Or use dark

# Optional settings

discus_identifier: # Add your Disqus identifier
ga_analytics: "UA-36555623-1"
rss_enabled: true # Change to false if not
about_enabled: false # Change to true if you wish to show an icon in the navigation that redirects to the about page
social:
  dribbble: # Add your Dribbble handle
  facebook: "boy"
  flickr: # Add your Flickr handle
  github: "Overload119"
  linkedin: "amir-sharif-29226636"
  twitter: # Add your Twitter handle
  email: "hello@amirsharif.com"
  bitcoin: # Add your Bitcoin link or address

# Important settings (change at own risk)

assets:
  compress:
    css: true
    js: true
  features:
    automatic_img_size: false
  assets:
    - _assets/fonts
  sources:
    - _assets/bower
    - _assets/fonts
    - _assets/images
    - _assets/javascripts
    - _assets/stylesheets
    - _vendor/
collections:
  my_tags:
    output: true
    permalink: /tag/:slug/
defaults:
  -
    scope:
      path: ""
      type: my_tags
    values:
      layout: articles_by_tag
exclude:
  - .bowerrc
  - .travis.yml
  - bin/*
  - bower.json
  - circle.yml
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor/
gems:
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji
permalink: posts/:slug
