# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

theme: minimal-mistakes-jekyll

defaults:
  - scope:
      path: "_assets/images"
    values:
      image: true

# Site Settings
minimal_mistakes_skin    : default # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
locale                   : "en-US"
title                    : "Amir Sharif"
title_separator          : "-"
name                     : "Amir Sharif"
description              : "The personal blog of Amir Sharif - engineer and self improvement enthusiast."
url                      : "https://amirsharif.com"
baseurl                  : # the subpath of your site, e.g. "/blog"
repository               : # GitHub username/repo-name e.g. "mmistakes/minimal-mistakes"
teaser                   : # path of fallback teaser image, e.g. "/assets/images/500x300.png"
# breadcrumbs            : false # true, false (default)
words_per_minute         : 200
comments:
  provider               : # false (default), "disqus", "discourse", "facebook", "google-plus", "staticman", "staticman_v2" "custom"
  disqus:
    shortname            : # https://help.disqus.com/customer/portal/articles/466208-what-s-a-shortname-
  discourse:
    server               : # https://meta.discourse.org/t/embedding-discourse-comments-via-javascript/31963 , e.g.: meta.discourse.org
  facebook:
    # https://developers.facebook.com/docs/plugins/comments
    # https://developers.facebook.com/apps/205344143356210/add/
    # username             : boy
    # appid                : 205344143356210
    # num_posts            : 5
    # colorscheme          : light
staticman:
  allowedFields          : # ['name', 'email', 'url', 'message']
  branch                 : # "master"
  commitMessage          : # "New comment."
  filename               : # comment-{@timestamp}
  format                 : # "yml"
  moderation             : # true
  path                   : # "/_data/comments/{options.slug}" (default)
  requiredFields         : # ['name', 'email', 'message']
  transforms:
    email                : # "md5"
  generatedFields:
    date:
      type               : # "date"
      options:
        format           : # "iso8601" (default), "timestamp-seconds", "timestamp-milliseconds"
reCaptcha:
  siteKey                :
  secret                 :
atom_feed:
  path                   : # blank (default) uses feed.xml
search                   : # true, false (default)
search_full_content      : # true, false (default)

# SEO Related
google_site_verification :
bing_site_verification   :
yandex_site_verification :
naver_site_verification  :

# Social Sharing
twitter:
  username               : amir_rezaa
facebook:
  username               :
  app_id                 :
  publisher              :
og_image                 : /assets/images/bio-photo.png
# For specifying social profiles
# - https://developers.google.com/structured-data/customize/social-profiles
social:
  type                   : # Person or Organization (defaults to Person)
  name                   : # If the user or organization name differs from the site's name
  links: # An array of links to social media profiles

# Analytics
analytics:
  provider: "google-gtag"
  google:
    tracking_id: "UA-36555623-1"
    anonymize_ip: false


# Site Author
author:
  name: "Amir Sharif"
  avatar: "/assets/images/bio-photo.png"
  bio: "Engineer at Facebook. Weekend hacker. Self improvement enthusiast."
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:hello@amirsharif.com"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/amir_rezaa"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/Overload119"

# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - Rakefile
  - README
  - tmp
  - /docs # ignore Minimal Mistakes /docs
  - /test # ignore Minimal Mistakes /test
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false


# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style


# Outputting
permalink: /:categories/:title/
paginate: 10 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji


# Archives
#  Type
#  - GitHub Pages compatible archive pages built with Liquid ~> type: liquid (default)
#  - Jekyll Archives plugin archive pages ~> type: jekyll-archives
#  Path (examples)
#  - Archive page should exist at path when using Liquid method or you can
#    expect broken links (especially with breadcrumbs enabled)
#  - <base_path>/tags/my-awesome-tag/index.html ~> path: /tags/
#  - <base_path/categories/my-awesome-category/index.html ~> path: /categories/
#  - <base_path/my-awesome-category/index.html ~> path: /
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
# https://github.com/jekyll/jekyll-archives
# jekyll-archives:
#   enabled:
#     - categories
#     - tags
#   layouts:
#     category: archive-taxonomy
#     tag: archive-taxonomy
#   permalinks:
#     category: /categories/:name/
#     tag: /tags/:name/


# HTML Compression
# - http://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: true

# name: "Amir Sharif"
# paginate: 25
# paginate_path: "/posts/page/:num/"
# url: "http://www.amirsharif.com"
# blog_theme: light # Or use dark
# theme: minimal-mistakes-jekyll
#
# # Optional settings
#
# discus_identifier: # Add your Disqus identifier
ga_analytics: "UA-36555623-1"
# rss_enabled: true # Change to false if not
# about_enabled: false # Change to true if you wish to show an icon in the navigation that redirects to the about page
#   bitcoin: # Add your Bitcoin link or address
#
# # Important settings (change at own risk)
#
# assets:
#   compress:
#     css: true
#     js: true
#   features:
#     automatic_img_size: false
#   assets:
#     - _assets/fonts
#   sources:
#     - _assets/bower
#     - _assets/fonts
#     - _assets/images
#     - _assets/javascripts
#     - _assets/stylesheets
#     - _vendor/
# collections:
#   my_tags:
#     output: true
#     permalink: /tag/:slug/
# defaults:
#   -
#     scope:
#       path: ""
#       type: my_tags
#     values:
#       layout: articles_by_tag
# exclude:
#   - .bowerrc
#   - .travis.yml
#   - bin/*
#   - bower.json
#   - circle.yml
#   - Gemfile
#   - Gemfile.lock
#   - README.md
#   - vendor/
# plugins:
#   - jekyll-assets
#   - jekyll-paginate
#   - jekyll-sitemap
#   - jemoji
# permalink: posts/:slug
