source 'https://rubygems.org'

gem 'autoprefixer-rails'
gem 'html-proofer'
gem 'jekyll'
gem 'jekyll-assets'
gem 'jekyll-livereload'
gem 'jekyll-paginate'
gem 'jekyll-sitemap'
gem 'jemoji'
gem 'mini_magick'
gem 'minimal-mistakes-jekyll'
gem 'octopress'
gem 'sass'
gem 'uglifier'
