source 'https://rubygems.org'

gem 'minimal-mistakes-jekyll'
gem 'autoprefixer-rails'
gem 'html-proofer'
gem 'jekyll', '~> 3.8.4'
gem 'jekyll-assets'
gem 'jekyll-feed'
gem 'jekyll-gist'
gem 'jekyll-livereload'
gem 'jekyll-paginate'
gem 'jekyll-sitemap'
gem 'jemoji'
gem 'octopress'
gem 'sass'
gem 'sprockets', '>= 3.7.2'
gem 'uglifier'
gem 'rack', '>= 2.0.8'
gem 'faraday', '0.17.3'
gem 'nokogiri', '>= 1.10.4'
gem 'mini_magick', '>= 4.9.4'
